/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class TestSceneUI extends Laya.Scene {
		public lable_score:laya.display.Text;
		public box_start:Laya.Box;
		public btn_start:Laya.Button;
		public box_continue:Laya.Box;
		public btn_reset:Laya.Button;
		public btn_continue:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}