/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class TestSceneUI extends Laya.Scene {
		public img_bottom:Laya.Image;
		public lable_score:laya.display.Text;
		public box_start:Laya.Box;
		public btn_start:Laya.Button;
		public box_continue:Laya.Box;
		public btn_reset:Laya.Button;
		public btn_continue:Laya.Button;
		public box_combo:Laya.Box;
		public img_digtal_0:Laya.Image;
		public img_digtal_1:Laya.Image;
		public img_digtal_2:Laya.Image;
		public box_tower:Laya.Box;
		public lable_0:laya.display.Text;
		public lable_1:laya.display.Text;
		public lable_2:laya.display.Text;
		public lable_3:laya.display.Text;
		public lable_4:laya.display.Text;
		public lable_5:laya.display.Text;
		public lable_6:laya.display.Text;
		public lable_7:laya.display.Text;
		public lable_8:laya.display.Text;
		public lable_9:laya.display.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/TestScene");
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}